---
title: test
author: ''
date: '2022-11-03'
slug: test
categories: []
tags: []
---
$h$

---
title: "Chapter 1 - Introduction"
katex: yes
---

Theorem 1.1 - 2-steps {#theorem-1.1-2-steps .unnumbered}
-----------------------

If an operation consists of two steps, of which the first can be done in
$n_1$ ways and for each of these the second can be done in $n_2$ ways,
then the whole operation can be done in $n_1 \cdot n_2$ ways.

Theorem 1.2 k-steps {#theorem-1.2-k-steps .unnumbered}
-----------------------

If an operation consists of $k$ steps, of which the first can be done in
$n_1$ ways, for each of these the second step can be done in $n_2$ ways,
for each of the first two the third step can be done in $n_3$ ways, and
so forth, then the whole operation can be done in
$n_1 \cdot n_2 \cdot \ldots \cdot n_k$ ways.

Theorem 1.3 \# of permutations {#theorem-1.3-of-permutations .unnumbered}
----------------------------------

The number of permutations of $n$ distinct objects is $n!$

Theorem 1.4 \# of permutations, $r$ at a time {#theorem-1.4-of-permutations-r-at-a-time .unnumbered}
-------------------------------------------------

The number of permutations of $n$ distinct objects taken $r$ at a time
is $${}_nP_r = \frac{n!}{(n-r)!}$$ for $r=0,1,2,\ldots,n$.

### Proof {#proof .unnumbered}

The formula ${}_nP_r=n(n-1) \cdot \ldots \cdot (n-r+1)$ cannot be used
for $r=0$, but we do have

$${}_nP_0 = \frac{n!}{(n-0)!}=1$$

For $r=1,2,\ldots,n,$ we have

$$\begin{aligned}
{}_nP_r&=n(n-1)(n-2) \cdot \ldots \cdot (n-r-1)\\
&=\frac{n(n-1)(n-2) \cdot \ldots \cdot (n-r-1)(n-r)!}{(n-r)!}\\
&=\frac{n!}{(n-r)!}\end{aligned}$$

Theorem 1.5 Circular Permutations {#theorem-1.5-circular-permutations .unnumbered}
-------------------------------------

The number of permutations of $n$ distinct objects arranged in a circle
is $(n-1)!$

Theorem 1.6 Permutations of $n$ objects {#theorem-1.6-permutations-of-n-objects .unnumbered}
-------------------------------------------

The number of permutations of $n$ objects of which $n_1$ are of one
kind, $n_2$ are of a second kind, $\ldots, n_k$ are of a $k$th kind, and
$n_1+n_2+\dots+n_k=n$ is

$$\frac{n!}{n_1! \cdot n_2! \cdot \ldots \cdot n_k!}$$

Theorem 1.7 Combination {#theorem-1.7-combination .unnumbered}
---------------------------

The number of combinations of $n$ distinct objects taken $r$ at a time
is

$$\dbinom n r = \frac{n!}{r!(n-r)!}$$

for $r=0,1,2,\ldots,n$

Theorem 1.8 $n$ objects into $k$ subsets {#theorem-1.8-n-objects-into-k-subsets .unnumbered}
--------------------------------------------

The number of ways in which a set of $n$ distinct objects can be
partitioned into $k$ subsets with $n_1$ objects in the first subset,
$n_2$ objects in the second subset, $\ldots$, and $n_k$ objects in the
$k$th subset is

$$\dbinom {n} {n_1, n_2, \ldots, n_k}=\frac{n!}{n_1! \cdot n_2! \cdot \ldots \cdot n_k!}$$

### Proof {#proof-1 .unnumbered}

Since the $n_1$ objects going into the first subset can be chosen in
$\dbinom n {n_1}$ ways, the $n_2$ objects going into the second subset
can then be chose in $\dbinom {n-n_1} {n_2}$ ways, the $n_3$ objects
going into the third subset can then be chosen in
$\dbinom {n-n_1-n_2} {n_3}$ ways, and so forth, it follows by Theorem
1.2 that the total number of partitions is

$$\begin{aligned}
\dbinom {n} {n_1,n_2,\ldots,n_k} &= \dbinom n {n_1} \cdot \dbinom {n - n_1} {n_2} \cdot \ldots \cdot \dbinom {n-n_1-n_2-\cdots -n_{k-1}}{n_k}\\
&= \frac{n!}{n_1! \cdot (n-n_1)!} \cdot \frac{(n-n_1)!}{n_2! \cdot (n-n_1-n_2)!} \cdot \ldots \cdot \frac{(n-n_1-n_2-\cdots-n_{k-1})!}{n_k! \cdot 0!}\\
&= \frac{n!}{n_1! \cdot n_2! \cdot \ldots \cdot n_k!}\end{aligned}$$

Theorem 1.9 Binomial Coefficient {#theorem-1.9-binomial-coefficient .unnumbered}
------------------------------------

$(x+y)^n=\sum^n_{r=0} \dbinom n r x^{n-r} y ^r$ for any positive integer
$n$

Theorem 1.10 Combination of the complimentary set {#theorem-1.10-combination-of-the-complimentary-set .unnumbered}
-----------------------------------------------------

For any positive integers $n$ and $r=0,1,2,\ldots,n,$

$$\dbinom n r = \dbinom n {n-r}$$

### Proof {#proof-2 .unnumbered}

We might argue that when we select a subset of $r$ objects from a set of
$n$ distinct objects, we leave a subset of $n-r$ objects; hence, there
are as many ways of selecting $r$ objects as there are ways of leaving
(or selecting) $n-r$ objects. To prove the theorem algebraically, we
write

$$\begin{aligned}
\dbinom n {n-r} &= \frac{n!}{(n-r)![n-(n-r)]!} = \frac{n!}{(n-r)!r!}\\
&= \frac{n!}{r!(n-r)!} = \dbinom n r\end{aligned}$$

Theorem 1.11 Combination for Pascal's Triangle {#theorem-1.11-combination-for-pascals-triangle .unnumbered}
--------------------------------------------------

For any positive integer $n$ and $r=1,2,\ldots, n-1$,

$$\dbinom n r = \dbinom {n-1} r + \dbinom {n-1} {r-1}$$

### Proof {#proof-3 .unnumbered}

Substituting $x=1$ into $(x+y)^n$, let us write
$(1+y)^n = (1+y)(1+y)^{n-1}=(1+y)^{n-1}+y(1+y)^{n-1}$ and equate the
coefficient of $y^r$ in $(1+y)^{n}$ with that in
$(1+y)^{n-1}+y(1+y)^{n-1}$. Since the coefficient of $y^r$ in
$(1+y)^{n}$ is $\dbinom n r$ and the coefficient of $y^r$ in
$(1+y)^{n-1}+(1+y)^{n-1}$ is the sum of the coefficient of $y^r$ in
$(1+y)^{n-1}$, that is, $\dbinom {n-1} r$, and the coefficient of
$y^{r-1}$ in $(1+y)^{n-1}$, that is, $\dbinom {n-1} {r-1}$, we obtain

$$\dbinom n r = \dbinom {n-1} r + \dbinom {n-1} {r-1}$$

which completes the proof.

Theorem 1.12 Sums of combinations {#theorem-1.12-sums-of-combinations .unnumbered}
-------------------------------------

$$\sum^k_{r=0} \dbinom m k \dbinom n {k-r} = \dbinom {m+n} k$$

### Proof {#proof-4 .unnumbered}

Using the same technique as in the proof of Theorem 1.11, let us prove
this theorem by equating the coefficients of $y^k$ in the expressions on
both sides of the equation

$$(1+y)^{m+n}=(1+y)^m(1+y)^n$$

The coefficient of $y^k$ in $(1+y)^{m+n}$ is $\dbinom {m+n} k$, and the
coefficient of $y^k$ in

$$(1+y)^m(1+y)^n = [ \dbinom m 0 + \dbinom m 1 y + \cdots + \dbinom m m y^m ] \times [ \dbinom n 0 + \dbinom n 1 y + \cdots + \dbinom n n y^n ]$$

is the sum of the prodcts that we obtain by multiplying the constant
term of the first factor by the coefficient of $y^k$ in the second
factor, the coefficient of $y$ in the first factor by the coefficient of
$y^{k-1}$ in the second factor, \..., and the coefficient of $y^k$ in
the first factor by the constant term of the second factor. Thus, the
coefficient of $y^k$ in $(1+y)^m(1+y)^n$ is

$$\dbinom m 0 \dbinom n k + \dbinom m 1 \dbinom n {k-1} + \dbinom m 2 \dbinom n {n-2} + \cdots + \dbinom m k \dbinom n 0 = \sum^k_{r=0} \dbinom m r \dbinom n {k-r}$$

and this completes the proof.
